### ISSUE TITLE
not a valid name or character

### ISSUE THREAD

**Issue by j0nix** [verifa/rt-retention#5]
Hey Verifa.

Got a problem with users creating paths and artifacts with 'special characters' , like '?'. 

I have not dig:ed into your code and looked into if you can intercept and "url-encode" these before executing deletes. 

> But if you do, would be nice since, as always, we the operators need to address and fix these issues. 

Example:
`
{
   "errors": [
     {
       "status": 500,
       "message": "Invalid path. '?' is not a valid name character: vce-art-level0-local/art/NGAH/feature/?NGAH-6806-seperate-pedal-behaviour/M1ECUx86/0.6.1-37-j0nix/j0nixrulez.zip"
     }
   ]
 }
 `

**Comment by praqma-thi** [comment]
Hey @j0nix,

First of all, my condolences on having users using special characters in their artifact paths.

That said, `rt-retention` doesn't call Artifactory itself, it delegates that to the underlying JFrog CLI. It generates [FileSpecs](https://jfrog.com/help/r/jfrog-integrations-documentation/using-file-specs) from the templates, and then calls the equivalent of [`jf rt delete --spec=<...>`](https://docs.jfrog-applications.jfrog.io/jfrog-applications/jfrog-cli/cli-for-jfrog-artifactory#deleting-files) for each generated spec. Unfortunately, I didn't find much on handling special characters in FileSpecs.

You're probably best off taking the FileSpec matching the problematic file to JFrog Support and asking them if there's a way to match that file properly. If there's a way to do it from the FileSpecs through some form of escaping, encoding or magic switch, I'd be happy to add it to `rt-retention`.

Worst case scenario, I did find an article on renaming and deleting such files manually through the DB [here](https://jfrog.com/help/r/artifactory-unable-to-delete-the-artifacts-file-with-the-special-character-in-artifactory/artifactory-unable-to-delete-the-artifacts/file-with-the-special-character-in-artifactory).

Hope that helps.

Cheers,
Thierry

**Comment by praqma-thi** [comment]
Oh, I've also released a new version of the plugin, which only updating the underlying version of the JFrog client it uses. I'd recommend giving it a shot with that before reaching out to JFrog.

**Comment by j0nix** [comment]
@praqma-thi - Thanx for clarification and kudos for doing ninja googling on my behalf. 

I close this one and mentally prepare myself for and 'e-mail war' with JFrog support. If it turns out that you somehow can cast some counter spells or apply vicious black magic to mitigate 'special character' related problems - I let you know...
